create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.admin_sessions (
  token text primary key,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null
);

create table if not exists public.chatbot_content (
  id integer generated by default as identity primary key,
  category text not null,
  label text not null,
  content text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_chatbot_content_category
  on public.chatbot_content (category);

create table if not exists public.portfolio_memory_entries (
  id integer generated by default as identity primary key,
  section_key text not null unique,
  title text not null,
  eyebrow text not null,
  summary text not null,
  context text not null,
  accent text not null check (accent in ('primary', 'secondary', 'accent')),
  facts jsonb not null default '[]'::jsonb,
  items jsonb not null default '[]'::jsonb,
  links jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_portfolio_memory_entries_sort_order
  on public.portfolio_memory_entries (sort_order);

create table if not exists public.chat_daily_usage (
  client_id text not null,
  date_key text not null,
  used_count integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (client_id, date_key)
);

create index if not exists idx_chat_daily_usage_date_key
  on public.chat_daily_usage (date_key);

create table if not exists public.visitor_lifetime (
  id integer generated by default as identity primary key,
  visitor_id text not null unique,
  first_seen_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.messages (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.contact_submissions (
  id integer generated by default as identity primary key,
  full_name text not null,
  email text not null,
  message text not null,
  fingerprint text not null,
  ip_address text not null,
  status text not null default 'unread' check (status in ('unread', 'read', 'replied')),
  read_at timestamptz,
  replied_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_contact_submissions_created_at
  on public.contact_submissions (created_at desc);

create index if not exists idx_contact_submissions_status
  on public.contact_submissions (status);

create table if not exists public.contact_daily_usage (
  client_key text not null,
  date_key text not null,
  used_count integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (client_key, date_key)
);

create index if not exists idx_contact_daily_usage_date_key
  on public.contact_daily_usage (date_key);

create table if not exists public.admin_settings (
  setting_key text primary key,
  value_text text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.projects (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  thumbnail text not null,
  tech_stack jsonb not null default '[]'::jsonb,
  live_url text,
  github_url text
);

create table if not exists public.achievements (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  date text not null
);

drop trigger if exists trigger_chatbot_content_updated_at on public.chatbot_content;
create trigger trigger_chatbot_content_updated_at
before update on public.chatbot_content
for each row
execute function public.set_updated_at();

drop trigger if exists trigger_portfolio_memory_entries_updated_at on public.portfolio_memory_entries;
create trigger trigger_portfolio_memory_entries_updated_at
before update on public.portfolio_memory_entries
for each row
execute function public.set_updated_at();

drop trigger if exists trigger_contact_submissions_updated_at on public.contact_submissions;
create trigger trigger_contact_submissions_updated_at
before update on public.contact_submissions
for each row
execute function public.set_updated_at();

drop trigger if exists trigger_admin_settings_updated_at on public.admin_settings;
create trigger trigger_admin_settings_updated_at
before update on public.admin_settings
for each row
execute function public.set_updated_at();

create or replace function public.consume_chat_daily_message(
  target_client_id text,
  date_key_input text,
  daily_limit integer
)
returns table (allowed boolean, used_count integer)
language plpgsql
security definer
as $$
declare
  next_used integer;
begin
  insert into public.chat_daily_usage (client_id, date_key, used_count)
  values (target_client_id, date_key_input, 1)
  on conflict (client_id, date_key)
  do update set
    used_count = case
      when public.chat_daily_usage.used_count >= daily_limit then public.chat_daily_usage.used_count
      else public.chat_daily_usage.used_count + 1
    end,
    updated_at = timezone('utc', now())
  returning public.chat_daily_usage.used_count into next_used;

  return query
  select next_used <= daily_limit, next_used;
end;
$$;

create or replace function public.track_unique_lifetime_visitor(target_visitor_id text)
returns integer
language plpgsql
security definer
as $$
declare
  total integer;
begin
  insert into public.visitor_lifetime (visitor_id)
  values (target_visitor_id)
  on conflict (visitor_id) do nothing;

  select count(*)::integer into total
  from public.visitor_lifetime;

  return total;
end;
$$;

create or replace function public.consume_contact_submission_limit(
  target_client_key text,
  date_key_input text,
  daily_limit integer
)
returns table (allowed boolean, used_count integer)
language plpgsql
security definer
as $$
declare
  next_used integer;
begin
  insert into public.contact_daily_usage (client_key, date_key, used_count)
  values (target_client_key, date_key_input, 1)
  on conflict (client_key, date_key)
  do update set
    used_count = case
      when public.contact_daily_usage.used_count >= daily_limit then public.contact_daily_usage.used_count
      else public.contact_daily_usage.used_count + 1
    end,
    updated_at = timezone('utc', now())
  returning public.contact_daily_usage.used_count into next_used;

  return query
  select next_used <= daily_limit, next_used;
end;
$$;

alter table public.messages enable row level security;
alter table public.contact_submissions enable row level security;
alter table public.contact_daily_usage enable row level security;
alter table public.admin_settings enable row level security;
alter table public.projects enable row level security;
alter table public.achievements enable row level security;
alter table public.chatbot_content enable row level security;
alter table public.portfolio_memory_entries enable row level security;
alter table public.chat_daily_usage enable row level security;
alter table public.visitor_lifetime enable row level security;
alter table public.admin_sessions enable row level security;

drop policy if exists "public read projects" on public.projects;
create policy "public read projects"
on public.projects
for select
using (true);

drop policy if exists "public read achievements" on public.achievements;
create policy "public read achievements"
on public.achievements
for select
using (true);

drop policy if exists "public insert messages" on public.messages;
create policy "public insert messages"
on public.messages
for insert
with check (true);

drop policy if exists "public insert contact_submissions" on public.contact_submissions;
create policy "public insert contact_submissions"
on public.contact_submissions
for insert
with check (true);
